# general settings
name: train_ResShift_x4_S2N_hismatch256_500k_B48G1LR4e-5amp_wandb
model_type: ResShiftModel
scale: 4
num_gpu: 1
manual_seed: 0

# network structures
network_g:
  type: UNetModelSwin
  image_size: 64
  in_channels: 4
  model_channels: 160
  out_channels: 4
  attention_resolutions: [ 64, 32, 16, 8 ]
  dropout: 0
  channel_mult: [ 1, 2, 2, 4 ]
  num_res_blocks: [ 2, 2, 2, 2 ]
  conv_resample: True
  dims: 2
  use_fp16: False
  num_head_channels: 32
  use_scale_shift_norm: True
  resblock_updown: False
  swin_depth: 2
  swin_embed_dim: 192
  window_size: 8
  mlp_ratio: 4
  cond_lq: True
  lq_size: 64

# autoencoder
autoencoder:
  type: VQModelTorch
  embed_dim: 4
  n_embed: 8192
  ddconfig:
    double_z: False
    z_channels: 4
    resolution: 256
    in_channels: 4
    out_ch: 4
    ch: 128
    ch_mult: [ 1,2,4 ]
    num_res_blocks: 2
    attn_resolutions: [ ]
    dropout: 0.0
    padding_mode: zeros

diffusion:
  sf: 4
  schedule_name: exponential
  schedule_kwargs:
    power: 0.3
  etas_end: 0.99
  steps: 15
  min_noise_level: 0.04
  kappa: 2.0
  weighted_mse: False
  predict_type: xstart
  timestep_respacing: ~
  scale_factor: 1.0
  normalize_input: True
  latent_flag: True

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~
  pretrain_network_ae: "experiments/pretrained_models/sen2naip256_vq_f4_dim4.pth"

# dataset and data loader settings
datasets:
  train:
    name: S2N_hismatch_train
    type: TacoSplitDataset
    taco_paths:
      - "data/SEN2NAIPv2/sen2naipv2-histmatch.0000.part.taco"
      - "data/SEN2NAIPv2/sen2naipv2-histmatch.0001.part.taco"
      - "data/SEN2NAIPv2/sen2naipv2-histmatch.0002.part.taco"
      - "data/SEN2NAIPv2/sen2naipv2-histmatch.0003.part.taco"
    split_percent: [ 0.999, 0.001 ]
    split: 0
    phase: "train"
    scale: 4
    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 48
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: S2N_hismatch_val
    type: TacoSplitDataset
    taco_paths:
      - "data/SEN2NAIPv2/sen2naipv2-histmatch.0000.part.taco"
      - "data/SEN2NAIPv2/sen2naipv2-histmatch.0001.part.taco"
      - "data/SEN2NAIPv2/sen2naipv2-histmatch.0002.part.taco"
      - "data/SEN2NAIPv2/sen2naipv2-histmatch.0003.part.taco"
    split_percent: [ 0.999, 0.001 ]
    split: 1
    phase: "val"
    scale: 4
    gt_size: 256

# training settings
train:
  use_amp: true
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 4e-5
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: 5000

# validation settings
val:
  val_freq: 5000
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false
      better: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: 10000
  use_tb_logger: true
  wandb:
    project: SEN2NAIPv2HisMatch
    resume_id: ~
