# general settings
name: train_SRCNN_x4_S2N_hismatch256_500k_B32G1amp_wandb
model_type: SRRSModel
scale: 4
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: S2N_hismatch_train
    type: TacoSplitDataset
    taco_paths:
      - "data/SEN2NAIPv2/sen2naipv2-histmatch.0000.part.taco"
      - "data/SEN2NAIPv2/sen2naipv2-histmatch.0001.part.taco"
      - "data/SEN2NAIPv2/sen2naipv2-histmatch.0002.part.taco"
      - "data/SEN2NAIPv2/sen2naipv2-histmatch.0003.part.taco"
    split_percent: [0.999, 0.001]
    split: 0
    phase: "train"
    scale: 4
    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: S2N_hismatch_val
    type: TacoSplitDataset
    taco_paths:
      - "data/SEN2NAIPv2/sen2naipv2-histmatch.0000.part.taco"
      - "data/SEN2NAIPv2/sen2naipv2-histmatch.0001.part.taco"
      - "data/SEN2NAIPv2/sen2naipv2-histmatch.0002.part.taco"
      - "data/SEN2NAIPv2/sen2naipv2-histmatch.0003.part.taco"
    split_percent: [0.999, 0.001]
    split: 1
    phase: "val"
    scale: 4
    gt_size: 256

# network structures
network_g:
  type: SRCNN
  num_in_ch: 4
  num_out_ch: 4
  upscale: 4

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  use_amp: true
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: 5000
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false
      better: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: 10000
  use_tb_logger: true
  wandb:
    project: SEN2NAIPv2HisMatch
    resume_id: ~

