# general settings
name: train_SRCNN_x3_L2S_single288_500k_B32G1amp_wandb
model_type: L2SSingleModel
scale: 3
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: L2S_single_train
    type: L2SSingleHMSplitDataset
    root_path: "data/single_time_no_sea_no_coreg"
    split_percent: [ 0.999, 0.001 ]
    split: 0
    phase: "train"
    psnr_thresh: 24
    ssim_thresh: 0.8
    gt_size: 288
    use_hflip: True
    use_rot: True

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: L2S_single_val
    type: L2SSingleHMSplitDataset
    root_path: "data/single_time_no_sea_no_coreg"
    split_percent: [ 0.999, 0.001 ]
    split: 1
    phase: "val"
    psnr_min: 24
    psnr_max: 38
    ssim_min: 0.8
    gt_size: 288
    use_hflip: True
    use_rot: True

# network structures
network_g:
  type: SRCNN
  num_in_ch: 6
  num_out_ch: 6
  upscale: 3

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  use_amp: true
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: 5000
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false
      better: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: 10000
  use_tb_logger: true
  wandb:
    project: L2S_Single_Nopan
    resume_id: ~

